import type { Lang } from '../i18n.ts'
import type { SheetWords } from './sheetCopy.ts'

// THE WORDS OF THE CHARACTER SHEET, « Aventure » skin — the same shape as the serious words (lib/sheetCopy.ts) and the same figures, since the figures
// are handed to the words already formatted (lib/sheetView.ts). A game's vocabulary on a household's money: playful, never sneering — a short bar is
// room to grow, not a defeat, and nothing here says « game over ». Outside the eager dictionaries: only the sheet page reads them, and only in this mode.

const FR: SheetWords = {
  title: 'Fiche de personnage',
  intro: 'Votre foyer comme un héros de jeu de rôle : cinq caractéristiques, de l’équipement, des quêtes et des hauts faits. Les chiffres sont exactement ceux de la version sérieuse.',
  solo: 'Héros solitaire',
  couple: 'Duo d’aventuriers',
  heroClass: { retired: 'Voyageur à la retraite', pensioned: 'Gardien de la rente', saver: 'Bâtisseur de nid' },
  heroLine: (age, planned) => `${age} · prévoit de poser le sac à ${planned}`,
  level: { label: 'Niveau', value: (n) => `${n}`, none: 'niveau encore à découvrir', hint: 'Un niveau par année d’avance entre l’âge le plus tôt où l’argent dure et l’âge de retraite prévu, jusqu’à dix.' },
  stats: {
    runway: { name: 'Endurance', hint: 'Le plus tôt où toute la compagnie peut poser le sac, l’argent durant jusqu’au bout du voyage.' },
    cover: { name: 'Armure', hint: 'La part des dépenses que les rentes paient seules, après impôt, une fois qu’elles sont toutes versées.' },
    saving: { name: 'Récolte', hint: 'Ce que ceux qui travaillent encore rapportent au camp chaque année, par rapport à leur salaire.' },
    keep: { name: 'Butin gardé', hint: 'La part de l’argent reçu qui reste après l’impôt sur le revenu et la récupération de la PSV.' },
    resilience: { name: 'Sang-froid', hint: 'Dans combien des trois scénarios (Prudent, Neutre, Audacieux) le plan tient jusqu’à la fin du voyage.' },
  },
  value: { age: (n) => `${n} ans`, years: (n) => `${n} ans`, share: (pct) => pct, count: (n, of) => `${n} sur ${of}`, pending: 'Le sort est en train d’être lancé…', none: 'Pas encore révélé', noAge: (max) => `Aucun âge jusqu’à ${max} ans` },
  scale: {
    runway: (years) => `Jauge pleine : ${years} d’avance.`,
    cover: 'Jauge pleine : toutes les dépenses payées par les rentes.',
    saving: (pct) => `Jauge pleine : ${pct} du salaire rapporté au camp.`,
    keep: 'Jauge pleine : aucun impôt.',
    resilience: (n) => `Jauge pleine : les ${n} scénarios.`,
  },
  detail: {
    runway: (planned, margin) => `Vous prévoyez poser le sac à ${planned} : ${margin} d’avance.`,
    runwayLate: (planned, earliest) => `Vous prévoyez poser le sac à ${planned}, mais l’argent ne tient qu’à partir de ${earliest} : de la place pour grandir.`,
    runwayNone: 'L’argent ne tient à aucun âge essayé : de la place pour grandir.',
    cover: (yearAge) => `Mesurée en ${yearAge}, la première année où toutes les rentes sont versées.`,
    saving: 'Vos cotisations et celles de votre employeur, sur le salaire de ceux qui travaillent encore.',
    keep: (yearAge) => `Mesuré en ${yearAge}, sur le revenu net des deux déclarations.`,
    resilience: (held) => `Le plan tient sous : ${held}.`,
    resilienceNone: 'Le plan ne tient sous aucun des trois scénarios : de la place pour grandir.',
    retired: 'Toute la compagnie est déjà en route vers le repos : la question n’est plus « quand ? ».',
    noEarner: 'Personne ne travaille plus : rien à récolter.',
  },
  slots: { title: 'Équipement', empty: 'Aucun coffre ni aucun talisman pour l’instant.', kind: { rrsp: 'Coffre REER', tfsa: 'Coffre CELI', nonReg: 'Bourse libre', pension: 'Talisman de rente', home: 'Forteresse (valeur nette)' }, confirmed: 'authentifié par un document', estimated: 'à authentifier', household: 'La compagnie' },
  quests: {
    title: 'Quêtes',
    intro: 'Trois façons de rendre la fiche plus juste ou le plan plus solide. Ce sont des pistes, pas des ordres.',
    complete: 'Quête d’éveil : entrez un revenu et vos dépenses à la retraite pour que la fiche prenne vie.',
    confirm: (n) => `Faire authentifier ${n} ${n > 1 ? 'chiffres' : 'chiffre'} par un document.`,
    room: (account, amount) => `Il reste ${amount} de place dans le coffre ${account}.`,
    plan: 'Consulter le grimoire du plan pour cette année.',
    none: 'Aucune quête en cours.',
    account: { rrsp: 'REER', tfsa: 'CELI' },
  },
  achievements: {
    title: 'Hauts faits',
    earned: 'Accompli',
    locked: 'À accomplir',
    names: { holds: 'Plan blindé', confirmed: 'Maître des preuves', debtFree: 'Libéré de l’hypothèque', diversified: 'Trois coffres', margin: 'Deux ans d’avance' },
    hints: {
      holds: 'Le plan tient sous les trois scénarios.',
      confirmed: 'Chaque chiffre est authentifié par un document.',
      debtFree: 'L’hypothèque est payée avant le départ à la retraite.',
      diversified: 'De l’argent au REER, au CELI et hors compte enregistré.',
      margin: 'L’âge prévu est au moins deux ans après l’âge le plus tôt.',
    },
  },
  accuracy: (confirmed, total) => `${confirmed} chiffres sur ${total} sont authentifiés par un document.`,
  scenarioNames: { prudent: 'Prudent', neutral: 'Neutre', bold: 'Audacieux' },
  empty: 'Le héros n’a pas encore d’histoire : entrez un revenu et vos dépenses à la retraite.',
  toProfile: 'Retourner au profil',
  toResults: 'Voir la réponse',
}

const EN: SheetWords = {
  title: 'Character sheet',
  intro: 'Your household as a role-playing hero: five attributes, equipment, quests and feats. The figures are exactly those of the serious version.',
  solo: 'Lone hero',
  couple: 'Pair of adventurers',
  heroClass: { retired: 'Retired wayfarer', pensioned: 'Keeper of the pension', saver: 'Nest builder' },
  heroLine: (age, planned) => `${age} · plans to set down the pack at ${planned}`,
  level: { label: 'Level', value: (n) => `${n}`, none: 'level still to be discovered', hint: 'One level for each year of headroom between the earliest age at which the money lasts and the planned retirement age, up to ten.' },
  stats: {
    runway: { name: 'Stamina', hint: 'The earliest the whole party can set down the pack, with the money lasting to the end of the journey.' },
    cover: { name: 'Armour', hint: 'The share of spending the pensions pay on their own, after tax, once they are all in pay.' },
    saving: { name: 'Harvest', hint: 'What those who still work bring back to camp each year, against their pay.' },
    keep: { name: 'Loot kept', hint: 'The share of the money received that is left after income tax and the OAS recovery.' },
    resilience: { name: 'Composure', hint: 'Under how many of the three scenarios (Prudent, Neutral, Bold) the plan lasts to the end of the journey.' },
  },
  value: { age: (n) => `${n}`, years: (n) => `${n} years`, share: (pct) => pct, count: (n, of) => `${n} of ${of}`, pending: 'The spell is being cast…', none: 'Not yet revealed', noAge: (max) => `No age up to ${max}` },
  scale: {
    runway: (years) => `Full gauge: ${years} of headroom.`,
    cover: 'Full gauge: all spending paid by the pensions.',
    saving: (pct) => `Full gauge: ${pct} of pay brought back to camp.`,
    keep: 'Full gauge: no tax.',
    resilience: (n) => `Full gauge: all ${n} scenarios.`,
  },
  detail: {
    runway: (planned, margin) => `You plan to set down the pack at ${planned}: ${margin} of headroom.`,
    runwayLate: (planned, earliest) => `You plan to set down the pack at ${planned}, but the money only lasts from ${earliest}: room to grow.`,
    runwayNone: 'The money lasts at no age tried: room to grow.',
    cover: (yearAge) => `Measured in ${yearAge}, the first year every pension is in pay.`,
    saving: 'Your contributions and your employer’s, against the pay of those who still work.',
    keep: (yearAge) => `Measured in ${yearAge}, on the net income of both returns.`,
    resilience: (held) => `The plan holds under: ${held}.`,
    resilienceNone: 'The plan holds under none of the three scenarios: room to grow.',
    retired: 'The whole party is already on the road to rest: the question is no longer “when?”.',
    noEarner: 'Nobody works any more: nothing to harvest.',
  },
  slots: { title: 'Equipment', empty: 'No chest or talisman yet.', kind: { rrsp: 'RRSP chest', tfsa: 'TFSA chest', nonReg: 'Open purse', pension: 'Pension talisman', home: 'Stronghold (net equity)' }, confirmed: 'authenticated by a document', estimated: 'to be authenticated', household: 'The party' },
  quests: {
    title: 'Quests',
    intro: 'Three ways to make the sheet more accurate or the plan sturdier. They are leads, not orders.',
    complete: 'Awakening quest: enter an income and your retirement spending so the sheet comes alive.',
    confirm: (n) => `Have ${n} ${n > 1 ? 'figures' : 'figure'} authenticated by a document.`,
    room: (account, amount) => `${amount} of room is left in the ${account} chest.`,
    plan: 'Consult the plan’s grimoire for this year.',
    none: 'No quest in progress.',
    account: { rrsp: 'RRSP', tfsa: 'TFSA' },
  },
  achievements: {
    title: 'Feats',
    earned: 'Achieved',
    locked: 'To achieve',
    names: { holds: 'Armoured plan', confirmed: 'Master of proofs', debtFree: 'Freed from the mortgage', diversified: 'Three chests', margin: 'Two years ahead' },
    hints: {
      holds: 'The plan holds under all three scenarios.',
      confirmed: 'Every figure is authenticated by a document.',
      debtFree: 'The mortgage is paid off before retirement.',
      diversified: 'Money in the RRSP, the TFSA and outside a registered account.',
      margin: 'The planned age is at least two years after the earliest age.',
    },
  },
  accuracy: (confirmed, total) => `${confirmed} of ${total} figures are authenticated by a document.`,
  scenarioNames: { prudent: 'Prudent', neutral: 'Neutral', bold: 'Bold' },
  empty: 'The hero has no story yet: enter an income and your retirement spending.',
  toProfile: 'Back to the profile',
  toResults: 'See the answer',
}

export const RPG_COPY: Record<Lang, SheetWords> = { fr: FR, en: EN }
