// Security headers on every response.
//
// Horizon keeps a household's financial profile in the browser and sends nothing anywhere,
// so the policy can be as tight as it is honest: `connect-src 'self'` means that even a
// compromised dependency cannot phone the profile home, which is the one property worth
// enforcing hard. What the app actually loads: its own scripts, its own stylesheet, its own
// self-hosted fonts (@fontsource, bundled — no Google Fonts), data: images, and the service
// worker. Nothing cross-origin, ever.
//
// `style-src 'unsafe-inline'` is a real concession and the reason is mundane: React sets
// `style=""` attributes (the Icon component, the chart's measured sizes). Scripts stay
// strictly `'self'`. If a zone's edge ever injects an inline script of its own (Cloudflare's
// Web Analytics beacon does when auto-install is on), the browser will refuse it and log a
// CSP error — the app does not need it — rather than the policy being loosened to admit it.
const CSP_DIRECTIVES = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "font-src 'self' data:",
  "img-src 'self' data:",
  "connect-src 'self'",
  "worker-src 'self'",
  "manifest-src 'self'",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
  "frame-ancestors 'none'",
].join('; ')

export const ENFORCED: ReadonlyArray<readonly [name: string, value: string]> = [
  ['Strict-Transport-Security', 'max-age=31536000; includeSubDomains'],
  ['X-Content-Type-Options', 'nosniff'],
  ['Referrer-Policy', 'no-referrer'],
  // The app uses no device capability at all.
  ['Permissions-Policy', 'camera=(), microphone=(), geolocation=(), payment=(), usb=()'],
  ['Content-Security-Policy', CSP_DIRECTIVES],
  // Nothing cross-origin is ever embedded or embedding: isolate the browsing context, refuse
  // cross-origin reads of our responses, and keep the pre-CSP framing header for old browsers.
  ['Cross-Origin-Opener-Policy', 'same-origin'],
  ['Cross-Origin-Resource-Policy', 'same-origin'],
  ['X-Frame-Options', 'DENY'],
]

// THE OTHER HALF OF THE SAME GUARANTEE. Cloudflare's assets router serves a request that
// MATCHES A REAL FILE — `/` → index.html, `/manifest.webmanifest` — **without invoking the
// Worker at all**. So `withSecurityHeaders` never runs for them, and the app's own front door
// would ship with no headers while every unknown route had all of them. A `_headers` file in
// the assets directory is the layer that reaches those responses — and ONLY those (Cloudflare
// applies `_headers` to static assets, not to Worker-generated responses). The two halves are
// complementary, which is why this string is built from the SAME `ENFORCED` list the wrapper
// uses: one source, two delivery paths. vite.config.ts emits it into dist/ at build time.
export function headersFileSource(): string {
  const lines = [
    '# Generated by vite.config.ts from worker/securityHeaders.ts — do not edit.',
    '/*',
    ...ENFORCED.map(([name, value]) => `  ${name}: ${value}`),
    // Caching: /assets/* is content-hashed (a changed file is a new URL), so it never needs
    // revalidating; the shell and the service worker are the opposite — they name those hashes,
    // so a stale copy would pin a visitor to a build whose chunks are gone.
    '/assets/*',
    '  Cache-Control: public, max-age=31536000, immutable',
    '/',
    '  Cache-Control: no-cache',
    '/index.html',
    '  Cache-Control: no-cache',
    '/sw.js',
    '  Cache-Control: no-cache',
    '',
  ]
  return lines.join('\n')
}

export function withSecurityHeaders(res: Response): Response {
  const headers = new Headers(res.headers)
  for (const [name, value] of ENFORCED) headers.set(name, value)
  return new Response(res.body, { status: res.status, statusText: res.statusText, headers })
}
